# Generated by Django 5.2.4 on 2025-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPairsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinpair_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinpair_name', models.CharField(max_length=50)),
                ('trade_start_time', models.DateTimeField()),
                ('trade_close_time', models.DateTimeField()),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tp', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('side', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=20)),
                ('gain_percentage', models.FloatField()),
                ('is_virtual', models.BooleanField(default=False)),
            ],
        ),
    ]
