# Generated by Django 5.2.4 on 2025-07-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_virtual',
        ),
    ]
